import { MAX_MEMBER_NAME } from "../constants";

export function normalizeName(value) {
  if (value === null || value === undefined) return null;
  let v = String(value).trim();
  if (!v) return null;
  v = v.replace(/[&/,\\-]/g, "_");
  v = v.replace(/\s+/g, "_");
  v = v.replace(/[^A-Za-z0-9_]/g, "");
  v = v.replace(/_+/g, "_");
  v = v.replace(/^_+|_+$/g, "");
  if (!v) return null;
  if (v.length > MAX_MEMBER_NAME) v = v.slice(0, MAX_MEMBER_NAME);
  return v;
}

export function escapeXml(value) {
  if (!value) return "";
  return String(value).trim()
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function formatBytes(b) {
  if (b < 1024) return `${b} B`;
  if (b < 1048576) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1048576).toFixed(1)} MB`;
}

export function generateMemberXml(members, dimName) {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Generated by OneStream Metadata Builder — ${new Date().toISOString()} -->`,
    `<members>`,
    ...Object.values(members).map(m =>
      `  <member name="${escapeXml(m.name)}" description="${escapeXml(m.desc)}" displayMemberGroup="Everyone"></member>`
    ),
    `</members>`,
  ].join("\n");
}

export function generateRelXml(relationships, dimName) {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Generated by OneStream Metadata Builder — ${new Date().toISOString()} -->`,
    `<relationships>`,
    ...relationships.map(r =>
      `  <relationship parent="${escapeXml(r.parent)}" child="${escapeXml(r.child)}"></relationship>`
    ),
    `</relationships>`,
  ].join("\n");
}

export function downloadFile(content, filename, type = "text/xml") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
